# Generated by Django 3.2.12 on 2023-03-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='time_Stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
