# Generated by Django 3.2.12 on 2023-03-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orderupdate_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='time_Stamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
